JCMSWeb/dev/JCMSWebTierJB6/src/java/jcms/web/common/ErrorBean.java
/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/
package jcms.web.common;


import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.SQLException;
import java.util.Map;
import javax.faces.context.FacesContext;
import javax.servlet.ServletException;

/**
 *
 * @author cnh
 */
public class ErrorBean
{

    public String getStackTrace()
    {
        FacesContext context = FacesContext.getCurrentInstance();
        Map<String, Object> request = context.getExternalContext().getRequestMap();

        Throwable ex = (Throwable) request.get("javax.servlet.error.exception");

        StringWriter sw = new StringWriter();
        PrintWriter pw = new PrintWriter(sw);

        fillStackTrace(ex,pw);

        return sw.toString();
    }

    private static void fillStackTrace(Throwable t, PrintWriter w)
    {
        if (t == null) return ;

        t.printStackTrace(w);

        if (t instanceof ServletException)
        {
            Throwable cause = ((ServletException) t).getRootCause();

            if (cause != null)
            {
                w.println("Root cause: ");
                fillStackTrace(cause, w);
            }
        }
        else if (t instanceof SQLException)
        {
            Throwable cause = ((SQLException) t).getNextException();

            if (cause != null)
            {
                w.println("Next exception: ");
                fillStackTrace(cause, w);
            }
        }
        else
        {
            Throwable cause = t.getCause();

            if (cause != null)
            {
                w.println("Cause: ");
                fillStackTrace(cause, w);
            }
        }
    }
    
}

JCMSWeb/dev/JCMSWebTierJB6/src/java/jcms/web/main/AboutBoxBean.java
/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/
package jcms.web.main;

import java.io.FileNotFoundException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.faces.application.FacesMessage;
import jcms.integrationtier.colonyManagement.JCMSDbInfoEntity;
import jcms.integrationtier.dao.Connector;
import jcms.integrationtier.dao.DataSourceProperty;
import jcms.integrationtier.jcmsWeb.DbInfoEntity;
import jcms.middletier.dto.ListSupportDTO;
import jcms.web.base.WTBaseBackingBean;

/**
 * Backing bean for AboutBox.xhtml
 */
public class AboutBoxBean extends WTBaseBackingBean implements Serializable
{
    private static final long serialVersionUID = 1L;

    private DbInfoEntity dbInfoEntity = new DbInfoEntity();
    private JCMSDbInfoEntity jcmsDbInfoEntity = new JCMSDbInfoEntity();
    private String hostName = "";
    private String adminLink = "";
    private ArrayList<String> connections = null;
    private String softwareVersionNumber = "3.14.0";

    public AboutBoxBean() {
        this.setAdminLink(this.populateAdminModuleLink());
        this.initialize();
    }

    private void initialize() {
        if (this.getRepositoryService().getDatabaseInformation() != null) {
            dbInfoEntity = this.getRepositoryService().getDatabaseInformation().getDbInfoEntity();

            List<JCMSDbInfoEntity> info = new ArrayList<JCMSDbInfoEntity>();
             info = new ListSupportDTO().getJCMSDbInfo();

             if (info.size()>0) {
                 this.setJcmsDbInfoEntity(info.get(0));
             }
        }
        this.setHostName(this.getDBHostname());
    }

    public String getDBHostname() {
        String hostname = "";
        try {
            java.net.InetAddress localMachine = java.net.InetAddress.getLocalHost();

            if (localMachine != null) {
                hostname = localMachine.getHostName();
            }
        }
        catch (java.net.UnknownHostException e) { 
            this.addToMessageQueue(e.getMessage(), FacesMessage.SEVERITY_ERROR);
            this.getLogger().logWarn(this.formatLogMessage("Exception ",
                    e.getMessage()));
        }
        return hostname;
    }

    public String populateAdminModuleLink() {
        String link = "";
        link = "http://" + this.getDBHostname() + ":8080/rs/";

        return link;
    }

    public DbInfoEntity getDbInfoEntity() {
        return dbInfoEntity;
    }
    
    public void setDbInfoEntity(DbInfoEntity dbInfoEntity) {
        this.dbInfoEntity = dbInfoEntity;
    }

    /**
     * @return the hostName
     */
    public String getHostName() {
        return hostName;
    }

    /**
     * @param hostName the hostName to set
     */
    public void setHostName(String hostName) {
        this.hostName = hostName;
    }

    /**
     * @return the jcmsDbInfoEntity
     */
    public JCMSDbInfoEntity getJcmsDbInfoEntity() {
        return jcmsDbInfoEntity;
    }

    /**
     * @param jcmsDbInfoEntity the jcmsDbInfoEntity to set
     */
    public void setJcmsDbInfoEntity(JCMSDbInfoEntity jcmsDbInfoEntity) {
        this.jcmsDbInfoEntity = jcmsDbInfoEntity;
    }

    /**
     * @return the adminLink
     */
    public String getAdminLink() {
        return adminLink;
    }

    /**
     * @param adminLink the adminLink to set
     */
    public void setAdminLink(String adminLink) {
        this.adminLink = adminLink;
    }

    /**
     * @return the connections
     */
    public ArrayList<String> getConnections() {
        Connector connector = new Connector();
        DataSourceProperty property = null;
        ArrayList<String> connectionURLs = new ArrayList<String> ();
        String dbDetail = "";
        try {
            property = connector.getDatabaseConnectionParameters(Connector.JCMSDEFAULTDS);
            if (property.getConnectionUrl().length() > 0)
                connectionURLs.add(formatConnectionUrl(Connector.JCMSDEFAULTDS.toString(), property.getConnectionUrl()));
        } catch (FileNotFoundException fnf1) {  }
        try {
            property = connector.getDatabaseConnectionParameters(Connector.JCMSWebDS);
            if (property.getConnectionUrl().length() > 0)
                connectionURLs.add(formatConnectionUrl(Connector.JCMSWebDS.toString(), property.getConnectionUrl()));
        } catch (FileNotFoundException fnf1) {  }
        try {
            property = connector.getDatabaseConnectionParameters(Connector.JCMSWebDBDS);
            if (property.getConnectionUrl().length() > 0)
                connectionURLs.add(formatConnectionUrl(Connector.JCMSWebDBDS.toString(), property.getConnectionUrl()));
        } catch (FileNotFoundException fnf1) {  }
        
        return connectionURLs;
    }

    /**
     * @param connections the connections to set
     */
    public void setConnections(ArrayList<String> connections) {
        this.connections = connections;
    }

    private String formatConnectionUrl(String name, String dbDetail) {
        dbDetail = dbDetail.replace("jdbc:mysql://", "");
        dbDetail = dbDetail.replace(":3306/", " : ");
        dbDetail = dbDetail.replace(";", "");
        dbDetail = name + " : " + dbDetail;
        return dbDetail;
    }

    /**
     * @return the softwareVersionNumber
     */
    public String getSoftwareVersionNumber() {
        return softwareVersionNumber;
    }

    /**
     * @param softwareVersionNumber the softwareVersionNumber to set
     */
    public void setSoftwareVersionNumber(String softwareVersionNumber) {
        this.softwareVersionNumber = softwareVersionNumber;
    }
}

JCMSWeb/dev/JCMSWebTierJB6/src/java/jcms/web/main/MainBarBean.java
/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/
package jcms.web.main;

import javax.faces.application.Application;
import javax.servlet.http.HttpSession;
import jcms.web.base.WTBaseBackingBean;

/**
 * Backing bean for mainbar.xhtml
 */
public class MainBarBean extends WTBaseBackingBean
{
    public MainBarBean()
    {

    }

    public String go()
    {
        String action = "main";

        return action;
    }

    public String logout()
    {
        HttpSession         session     = (HttpSession) this.getFacesContext().getExternalContext().getSession(false);

        // Invalid session to force user to log back in.
        session.invalidate();

        Application app = this.getFacesContext().getApplication();
        app.getNavigationHandler().handleNavigation(this.getFacesContext(), "/welcome.xhtml", "welcome");

        // To avoid using the navigation handler you could also use...
        //response.sendRedirect("../index.xhtml");

        return null;
    }

}

JCMSWeb/dev/JCMSWebTierJB6/src/java/jcms/web/main/MainBean.java
/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/

package jcms.web.main;

import javax.faces.application.FacesMessage;
import jcms.web.base.WTBaseBackingBean;
import jcms.web.reports.BubbleStrain;
import jcms.web.reports.HistogramBean;
import jcms.integrationtier.dao.DashboardDAO;


/**
 * <b>File name:</b>  MainBean.java  <p>
 * <b>Date developed:</b>  February 2009 <p>
 * <b>Purpose:</b>  Backing bean for MainBean web page.  <p>
 * <b>Overview:</b> Initializes user session object.  <p>
 * <b>Last changed by:</b>   $Author: rkavitha $ <p>
 * <b>Last changed date:</b> $Date: 2011-01-19 15:17:04 -0500 (Wed, 19 Jan 2011) $   <p>
 * @author Craig Hanna
 * @version $Revision: 11948 $
 */
public class MainBean extends WTBaseBackingBean {
    // Constructor
    public MainBean()
    {

    }
    
    public void buildDashboardData(){
        BubbleStrain bubbleBean = new BubbleStrain(true);
        HistogramBean histoBean = new HistogramBean();
        bubbleBean.buildBubbleStrainLite();
        histoBean.buildCageHistogramData();
        histoBean.buildMouseHistogramData();
    }
    
    public void updateDashboardData(){
        try{
            new DashboardDAO().updateDashboard();
        }
        catch(Exception e){
            this.addToMessageQueue("Error: " + e, FacesMessage.SEVERITY_ERROR);
        }
    }
}

JCMSWeb/dev/JCMSWebTierJB6/src/java/jcms/web/main/WelcomeBean.java
/****
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
****/

package jcms.web.main;

import java.util.ArrayList;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import jcms.integrationtier.dao.CVAdministrationDAO;
import jcms.integrationtier.dto.AdminDbInfoDTO;
import jcms.web.admin.AdminBean;

/**
 *
 * @author cnh
 */
@ManagedBean
@SessionScoped
public class WelcomeBean extends AdminBean {
    
    public WelcomeBean() {
    }
    
    public Boolean getEnvironmentCheck() {
        Boolean showLogin = true;
        CVAdministrationDAO dao = new CVAdministrationDAO();
        ArrayList<AdminDbInfoDTO> dtoList = dao.getDbInfo();
        if (dtoList != null) {
            for (AdminDbInfoDTO dto : dtoList) {
                if(!dto.getWebReleaseNum().equals("3.14.0")){
                    showLogin = false;
                }
                break;
            }
        }
        return (showLogin);
    }

}

JCMSWeb/dev/JCMSWebTierJB6/web/403.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--***
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
***-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets">
    <h:head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title>JCMS No Access Page</title>
        <link href="/jcms/stylesheet/jcmsStyles.css" rel="stylesheet" media="screen" />
        <link rel="shortcut icon" href="/jcms/images/favicon.ico" />
        <script type="text/javascript" src="/jcms/javascript/jcmsWeb.js" >
        </script>
    </h:head>

    <h:body>
        <table width="100%" cellspacing="0" cellpadding="0">
            <tr bgcolor="#D8E3E6">
                <td rowspan="2"><img src="/jcms/images/header.jpg" alt="Header image" /></td>
                <td height="40" valign="bottom" align="right" nowrap="nowrap" id="logo">The Jackson Laboratory&nbsp;</td>
            </tr>
            <tr bgcolor="#D8E3E6">
                <td height="31" valign="top" align="right"><h3>COLONY MANAGEMENT SYSTEM&nbsp;&nbsp;&nbsp;</h3></td>
            </tr>
        </table>

        <table width="100%" border="0" cellspacing="0" cellpadding="0">
            <tr><td bgcolor="#808000"><img src="/jcms/images/spacer.gif" alt="" height="2" width="1" /></td></tr>
            <tr>
                <td colspan="2" align="right">
                    <table width="100%" class="barBackground">
                        <tr>
                            <td align="right" class="menu">&nbsp;</td>
                        </tr>
                    </table>
                </td>
            </tr>
            <tr><td bgcolor="#808000"><img src="/jcms/images/spacer.gif" alt="" height="2" width="1" /></td></tr>
        </table>

        <br />
        <div style="margin-left:10px;margin-right:10px">

            <h1>Application Login</h1>
            <hr/><br/>
        <h3>We&#039;re sorry that your request could not be processed.
            The processing error message is:</h3>   
            <!-- displays any error messages -->
        <ul>
            <li><span class="errorMessage">You do not have permissions to go further</span></li>
        </ul>
        <br />

        <table width="100%">
            <tbody><h2>Authorization failed. Please press your browser's <em>back</em> button and retry.</h2>
        </tbody>
        </table>
        </div>
        <f:subview id="footer"><ui:include src="footer.xhtml"/></f:subview>
    </h:body>
</html>

JCMSWeb/dev/JCMSWebTierJB6/web/errorPage.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--***
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
***-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html">

    <f:subview id="dummy">
        <h:head>
            <title><br />
                <h:outputText value="#{msgs.error.title}"/>
            </title>
        </h:head>
        <h:body>
            <h1>System Error</h1>
            <h:form>
                <p><h:outputText value="#{msgs.error.errorOccurred}"/></p>
                <p><h:outputText value="#{msgs.error.copyReport}"/></p>
                <h:inputTextarea value="#{ErrorBean_Backing.stackTrace}"
                                 readonly="true"/>
            </h:form>
        </h:body>
    </f:subview>
</html>

JCMSWeb/dev/JCMSWebTierJB6/web/footer.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--***
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
***-->
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<div align="center">
    <table width="100%">
        <tr><td colspan="2"><hr></hr></td></tr>
        <tr>
            <td>
                <table align="left">
                    <tr>
                        <td>
                            <img src="/jcms/images/jax-logo.gif" alt="TJL image" />
                        </td>
                    </tr>
                </table>
            </td>
            <td>
                <table align="right">
                    <tr>
                        <td align="right">
                            The development and distribution of this software is made possible by generous grants from <br />
                            The National Institute for General Medical Sciences (NIGMS) [Grant number: 2R01GM072863-05A1] <br />
                            The National Cancer Institute (NCI)  [Grant number: P30 CA034196-20] and <br />
                            The Howard Hughes Medical Institute
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</div>
</ui:composition>    

JCMSWeb/dev/JCMSWebTierJB6/web/loginbar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--***
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
***-->
<ui:composition 
    xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets">
<table width="100%" border="0" cellspacing="0" cellpadding="0"
       xmlns:h="http://java.sun.com/jsf/html">
    <tr>
        <td bgcolor="#808000">
            <h:graphicImage url="#{msgs['mainbar.spacer']}" alt="" width="1" height="2"/>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="right">
            <table width="100%" class="barBackground">
                <tr>                        
                    <td align="center" class="menu">
                        <h:commandLink action="login" immediate="true"
                                       disabled="#{!(welcomeBean.environmentCheck)}">
                            <h:outputText value="#{msgs['loginbar.login']}"/>
                        </h:commandLink>
                    </td>
                    <td class="menu">
                        <h:outputLink onclick="window.open('/jcms/jcmsWeb/homeAbout.xhtml', 'AboutBox', 'height=550, width=750, dependent=yes, menubar=no, toolbar=no'); return false;" value="#">
                            <h:outputText value="#{msgs['about.about']}" />
                        </h:outputLink>
                    </td>
                </tr>
            </table>
        </td>
    </tr>
    <tr>
        <td bgcolor="#808000">
            <h:graphicImage url="#{msgs['mainbar.spacer']}" alt="" width="1" height="2"/>
        </td>
    </tr>
</table>
</ui:composition>

JCMSWeb/dev/JCMSWebTierJB6/web/sessionExpired.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--***
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
***-->

<!--
 String hostMainPage="http://" + request.getServerName() + ":8080/jcms/jcmsWeb/welcome.xhtml";
 response.sendRedirect(hostMainPage);
 -->
 

JCMSWeb/dev/JCMSWebTierJB6/web/welcome.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!--***
Copyright (c) 2015 The Jackson Laboratory

This is free software: you can redistribute it and/or modify it 
under the terms of the GNU General Public License as published by  
the Free Software Foundation, either version 3 of the License, or  
(at your option) any later version.
 
This software is distributed in the hope that it will be useful,  
but WITHOUT ANY WARRANTY; without even the implied warranty of 
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU 
General Public License for more details.

You should have received a copy of the GNU General Public License 
along with this software.  If not, see <http://www.gnu.org/licenses/>.
***-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:rich="http://richfaces.org/rich">
  <h:head>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1252" />
    <title>
      <h:outputText value="#{msgs['title']} - #{msgs['welcome.pageTitle']}"/>
    </title>
    <link href="/jcms/stylesheet/jcmsStyles.css" rel="stylesheet" media="screen" />
    <link rel="shortcut icon" href="/jcms/images/favicon.ico" />
  </h:head>
  <h:body>
    <h:form>
      <f:subview id="mainheader"><ui:include src="mainheader.xhtml"/></f:subview>
      <f:subview id="loginbar"><ui:include src="loginbar.xhtml"/></f:subview>
      <div style="margin-left:10px;margin-right:10px">
      <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
              <td>
                  <p>&nbsp;</p>
                  <h1><h:outputText value="#{msgs['welcome.header']}"/></h1>
                  <p><h2><h:outputText value="#{msgs['welcome.description']}"/></h2></p>
                  <p>&nbsp;</p>
                  <p>
                      <h:commandLink 
                          rendered="#{welcomeBean.environmentCheck}"
                          action="login" 
                          immediate="true">
                          <h:outputText value="#{msgs['loginbar.login']}"/>
                      </h:commandLink>
                      
                    <rich:panel rendered="#{!(welcomeBean.environmentCheck)}">
                        <h:outputText styleClass="errorMessageLabel"
                                      value="Environment Mismatch" />
                        <br /><br />
                        <h:outputText styleClass="errorMessageBody" style="margin-left: 40px;"
                                      value="JCMS Web is running against an incompatible database version.  Please install the latest JCMS Web version using JCMS Web Installer."/>
                        <br /><br />
                        <a href="http://colonymanagement.jax.org/" target="_blank" style="margin-left: 20px;">JAX Colony Management System</a>
                    </rich:panel>
                  </p>
                  <p>&nbsp;</p>
              </td>
          </tr>
      </table>
      </div>
      <f:subview id="footer"><ui:include src="footer.xhtml"/></f:subview>
    </h:form>
    </h:body>
</html>



